qualitycheck:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull binhsonnguyen/sonarqube-scanner
    - docker run -v $PWD:/root/src binhsonnguyen/sonarqube-scanner